In [11]:
import pandas as pd
data=pd.read_csv("emotion_sentimen_dataset.csv")

In [12]:
data.head()

   Unnamed: 0                                               text  Emotion
0           0  i seriously hate one subject to death but now ...     hate
1           1                 im so full of life i feel appalled  neutral
2           2  i sit here to write i start to dig out my feel...  neutral
3           3  ive been really angry with r and i feel like a...    anger
4           4  i feel suspicious if there is no one outside l...  neutral

In [13]:
df=data.head(5000)
df

      Unnamed: 0                                               text  Emotion
0              0  i seriously hate one subject to death but now ...     hate
1              1                 im so full of life i feel appalled  neutral
2              2  i sit here to write i start to dig out my feel...  neutral
3              3  ive been really angry with r and i feel like a...    anger
4              4  i feel suspicious if there is no one outside l...  neutral
...          ...                                                ...      ...
4995        4995  i have to admit i feel a little hesitant about...  neutral
4996        4996  i feel especially strongly about this since i ...     hate
4997        4997  ive realized over the last few months that i g...  neutral
4998        4998   i no longer feel timid or insecure when i walked  neutral
4999        4999  im feeling wimpy about this i know a one year ...  neutral

[5000 rows x 3 columns]

In [14]:
df['Emotion'].value_counts()

Emotion
neutral       4151
love           153
happiness      138
hate           116
relief         112
anger           95
enthusiasm      64
sadness         53
fun             52
worry           39
empty           20
surprise         7
Name: count, dtype: int64

In [15]:
df['new']=df['Emotion'].apply(lambda x: 1 if x=='love' else 0)

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\3864686326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new']=df['Emotion'].apply(lambda x: 1 if x=='love' else 0)

In [16]:
df.head(20)

,Unnamed: 0,text,Emotion,new
0,0,i seriously hate one subject to death but now ...,hate,0
1,1,im so full of life i feel appalled,neutral,0
2,2,i sit here to write i start to dig out my feel...,neutral,0
3,3,ive been really angry with r and i feel like a...,anger,0
4,4,i feel suspicious if there is no one outside l...,neutral,0
5,5,i feel jealous becasue i wanted that kind of l...,love,1
6,6,when a friend of mine keeps telling me morbid ...,neutral,0
7,7,i finally fell asleep feeling angry useless an...,worry,0
8,8,i feel a bit annoyed and antsy in a good way,neutral,0
9,9,i feel like i ve regained another vital part o...,neutral,0
10,10,i feel a bit like franz liebkind in the produc...,neutral,0
11,11,i was feeling at the start didnt want to move ...,neutral,0
12,12,i was bitten by a dog,neutral,0
13,13,i do not always find myself feeling thankful b...,neutral,0
14,14,i just try not to talk to anyone when i feel i...,neutral,0
15,15,i feel like they hated me since then,hate,0
16,16,i dont know who wrote the following little not...,neutral,0
17,17,i feel offended i choose to tell you guys how ...,neutral,0
18,18,i remember feeling as if i didn t belong and t...,neutral,0
19,19,i feel like i have to redeem myself even thoug...,neutral,0

In [17]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()
stopword=set(stopwords.words('english'))

In [20]:
df['tokens']=df['text'].apply(word_tokenize)

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\2491723692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens']=df['text'].apply(word_tokenize)

In [21]:
df.head()

,Unnamed: 0,text,Emotion,new,tokens
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ..."
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]"
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o..."
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe..."
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ..."

In [22]:
df['tokens'] = df['tokens'].apply(lambda x: x if isinstance(x, list) else [])

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\2722072290.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens'] = df['tokens'].apply(lambda x: x if isinstance(x, list) else [])

In [23]:
df.head()

,Unnamed: 0,text,Emotion,new,tokens
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ..."
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]"
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o..."
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe..."
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ..."

In [24]:
df['stopwords']=df['tokens'].apply(lambda x:[word.lower() for word in x if word.lower() not in stopword and word.isalpha()])

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\2248869959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stopwords']=df['tokens'].apply(lambda x:[word.lower() for word in x if word.lower() not in stopword and word.isalpha()])

In [25]:
df

,Unnamed: 0,text,Emotion,new,tokens,stopwords
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r..."
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]"
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra..."
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru..."
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture..."
...,...,...,...,...,...,...
4995,4995,i have to admit i feel a little hesitant about...,neutral,0,"[i, have, to, admit, i, feel, a, little, hesit...","[admit, feel, little, hesitant, embedding, mus..."
4996,4996,i feel especially strongly about this since i ...,hate,0,"[i, feel, especially, strongly, about, this, s...","[feel, especially, strongly, since, hated, tee..."
4997,4997,ive realized over the last few months that i g...,neutral,0,"[ive, realized, over, the, last, few, months, ...","[ive, realized, last, months, generally, tend,..."
4998,4998,i no longer feel timid or insecure when i walked,neutral,0,"[i, no, longer, feel, timid, or, insecure, whe...","[longer, feel, timid, insecure, walked]"
4999,4999,im feeling wimpy about this i know a one year ...,neutral,0,"[im, feeling, wimpy, about, this, i, know, a, ...","[im, feeling, wimpy, know, one, year, old, sen..."

In [26]:
df['stemming']=df['stopwords'].apply(lambda x:[ps.stem(word) for word in x])

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\3326232732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stemming']=df['stopwords'].apply(lambda x:[ps.stem(word) for word in x])

In [27]:
df

,Unnamed: 0,text,Emotion,new,tokens,stopwords,stemming
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel..."
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]"
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ..."
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru..."
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap..."
...,...,...,...,...,...,...,...
4995,4995,i have to admit i feel a little hesitant about...,neutral,0,"[i, have, to, admit, i, feel, a, little, hesit...","[admit, feel, little, hesitant, embedding, mus...","[admit, feel, littl, hesit, embed, music, vide..."
4996,4996,i feel especially strongly about this since i ...,hate,0,"[i, feel, especially, strongly, about, this, s...","[feel, especially, strongly, since, hated, tee...","[feel, especi, strongli, sinc, hate, teeth, fo..."
4997,4997,ive realized over the last few months that i g...,neutral,0,"[ive, realized, over, the, last, few, months, ...","[ive, realized, last, months, generally, tend,...","[ive, realiz, last, month, gener, tend, feel, ..."
4998,4998,i no longer feel timid or insecure when i walked,neutral,0,"[i, no, longer, feel, timid, or, insecure, whe...","[longer, feel, timid, insecure, walked]","[longer, feel, timid, insecur, walk]"
4999,4999,im feeling wimpy about this i know a one year ...,neutral,0,"[im, feeling, wimpy, about, this, i, know, a, ...","[im, feeling, wimpy, know, one, year, old, sen...","[im, feel, wimpi, know, one, year, old, sent, ..."

In [28]:
df['lemma']=df['stopwords'].apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\752103920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lemma']=df['stopwords'].apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

In [29]:
df.head()

,Unnamed: 0,text,Emotion,new,tokens,stopwords,stemming,lemma
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...","[seriously, hate, one, subject, death, feel, r..."
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]","[im, full, life, feel, appalled]"
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...","[sit, write, start, dig, feeling, think, afrai..."
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...","[ive, really, angry, r, feel, like, idiot, tru..."
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...","[feel, suspicious, one, outside, like, rapture..."

In [30]:
df['processed_text']=df['lemma'].apply(lambda x:" ".join(x))  #corrected to join the actual lemmas

C:\Users\admin\AppData\Local\Temp\ipykernel_5652\3242735494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed_text']=df['lemma'].apply(lambda x:" ".join(x))  #corrected to join the actual lemmas

In [31]:
Vectorizer=CountVectorizer()
x=Vectorizer.fit_transform(df['processed_text'])

In [32]:
df.head()

,Unnamed: 0,text,Emotion,new,tokens,stopwords,stemming,lemma,processed_text
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...","[seriously, hate, one, subject, death, feel, r...",seriously hate one subject death feel reluctan...
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]","[im, full, life, feel, appalled]",im full life feel appalled
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...","[sit, write, start, dig, feeling, think, afrai...",sit write start dig feeling think afraid accep...
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...","[ive, really, angry, r, feel, like, idiot, tru...",ive really angry r feel like idiot trusting fi...
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...","[feel, suspicious, one, outside, like, rapture...",feel suspicious one outside like rapture happe...

In [33]:
words=Vectorizer.get_feature_names_out()

In [34]:
words

array(['aa', 'aac', 'ab', ..., 'zonisamide', 'zq', 'zumba'],
      shape=(7224,), dtype=object)

In [35]:
bow=pd.DataFrame(x.toarray(),columns=words)

In [36]:
print(bow.head())

   aa  aac  ab  abandon  abandonment  abc  abdomen  abelard  abide  ability  \
0   0    0   0        0            0    0        0        0      0        0
1   0    0   0        0            0    0        0        0      0        0
2   0    0   0        0            0    0        0        0      0        0
3   0    0   0        0            0    0        0        0      0        0
4   0    0   0        0            0    0        0        0      0        0

   ...  zendikar  zero  zest  zhu  zipline  zombie  zone  zonisamide  zq  \
0  ...         0     0     0    0        0       0     0           0   0
1  ...         0     0     0    0        0       0     0           0   0
2  ...         0     0     0    0        0       0     0           0   0
3  ...         0     0     0    0        0       0     0           0   0
4  ...         0     0     0    0        0       0     0           0   0

   zumba
0      0
1      0
2      0
3      0
4      0

[5 rows x 7224 columns]

In [37]:
df.head()

,Unnamed: 0,text,Emotion,new,tokens,stopwords,stemming,lemma,processed_text
0,0,i seriously hate one subject to death but now ...,hate,0,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...","[seriously, hate, one, subject, death, feel, r...",seriously hate one subject death feel reluctan...
1,1,im so full of life i feel appalled,neutral,0,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]","[im, full, life, feel, appalled]",im full life feel appalled
2,2,i sit here to write i start to dig out my feel...,neutral,0,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...","[sit, write, start, dig, feeling, think, afrai...",sit write start dig feeling think afraid accep...
3,3,ive been really angry with r and i feel like a...,anger,0,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...","[ive, really, angry, r, feel, like, idiot, tru...",ive really angry r feel like idiot trusting fi...
4,4,i feel suspicious if there is no one outside l...,neutral,0,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...","[feel, suspicious, one, outside, like, rapture...",feel suspicious one outside like rapture happe...

In [38]:
a=df[['text','tokens','stopwords','stemming','lemma','processed_text']]

In [39]:
a.head()

,text,tokens,stopwords,stemming,lemma,processed_text
0,i seriously hate one subject to death but now ...,"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...","[seriously, hate, one, subject, death, feel, r...",seriously hate one subject death feel reluctan...
1,im so full of life i feel appalled,"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]","[im, full, life, feel, appalled]",im full life feel appalled
2,i sit here to write i start to dig out my feel...,"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...","[sit, write, start, dig, feeling, think, afrai...",sit write start dig feeling think afraid accep...
3,ive been really angry with r and i feel like a...,"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...","[ive, really, angry, r, feel, like, idiot, tru...",ive really angry r feel like idiot trusting fi...
4,i feel suspicious if there is no one outside l...,"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...","[feel, suspicious, one, outside, like, rapture...",feel suspicious one outside like rapture happe...

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(bow,df['new'],test_size=0.2,random_state=42)

In [41]:
x_test.shape

(1000, 7224)

In [42]:
x_train.shape

(4000, 7224)

In [43]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.989
[[966   1]
 [ 10  23]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       967
           1       0.96      0.70      0.81        33

    accuracy                           0.99      1000
   macro avg       0.97      0.85      0.90      1000
weighted avg       0.99      0.99      0.99      1000

In [45]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.997
[[967   0]
 [  3  30]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       967
           1       1.00      0.91      0.95        33

    accuracy                           1.00      1000
   macro avg       1.00      0.95      0.98      1000
weighted avg       1.00      1.00      1.00      1000

In [47]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB(alpha=2)
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.962
[[962   5]
 [ 33   0]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       967
           1       0.00      0.00      0.00        33

    accuracy                           0.96      1000
   macro avg       0.48      0.50      0.49      1000
weighted avg       0.93      0.96      0.95      1000

In [49]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB(alpha=2)
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.968
[[967   0]
 [ 32   1]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       967
           1       1.00      0.03      0.06        33

    accuracy                           0.97      1000
   macro avg       0.98      0.52      0.52      1000
weighted avg       0.97      0.97      0.95      1000

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2000)

In [66]:
trans=tfidf.fit_transform(['processed_text'])

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(bow,df['new'],test_size=0.2,random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [69]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.989
[[966   1]
 [ 10  23]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       967
           1       0.96      0.70      0.81        33

    accuracy                           0.99      1000
   macro avg       0.97      0.85      0.90      1000
weighted avg       0.99      0.99      0.99      1000

In [70]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [71]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.997
[[967   0]
 [  3  30]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       967
           1       1.00      0.91      0.95        33

    accuracy                           1.00      1000
   macro avg       1.00      0.95      0.98      1000
weighted avg       1.00      1.00      1.00      1000